export enum ActionType {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  UPDATE_CART_ITEM = "UPDATE_CART_ITEM",
  SET_ORDER = "SET_ORDER",
  GET_ORDER = "GET_ORDER",
  GET_DISHES = "GET_DISHES",
  LOGIN_USER = "LOGIN_USER",
  LOGOUT_USER = "LOGOUT_USER",
}
